apiVersion: v1
kind: Service
metadata:
  name: kanban-proxy-rev-7623group9
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
    app: kanban-webapp
  ports:
    - name: kanban-proxy-rev-7623group9-port-tcp-http
      protocol: TCP
      port: 80 ## Services can route with their own ports (this could be another number) port-forward/tunnel uses this + targetPort
      targetPort: 80 ## Match targetPort to Pod/Container Port
      nodePort: 32001 ## Connection to cluster for use with ingress/LB - external PROD traffic ideally eventually comes through here (remember node is the server/VM/instance)
    - name: kanban-proxy-rev-7623group9-port-tcp-https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32002
    - name: kanban-proxy-rev-7623group9-port-redirect-https-monex
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32333

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-app-client-7623group9
spec:
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: kanban-webapp
  ports:
    - name: kanban-webapp-port-tcp-http
      protocol: TCP
      port: 3000
      targetPort: 3000