apiVersion: v1
kind: Service
metadata:
  name: kanban-app-server-7623group9
spec:
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: kanban-webservices
  ports:
    - name: kanban-app-server-7623group9-port-tcp-http
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-data-mongodb-7623group9
spec:
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: kanban-webservices
  ports:
    - name: kanban-data-mongodb-7623group9-port-tcp-http
      protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-obs-mongoexpress-7623group9
spec:
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: kanban-webservices
  ports:
    - name: kanban-obs-mongoexpress-7623group9-port-tcp-http
      protocol: TCP
      port: 8081
      targetPort: 8081